FROM gcc:latest

WORKDIR /app

RUN set -eux && \
    apt-get update && \
    apt-get install -y libboost-dev libboost-program-options-dev cmake

COPY . .

RUN bin/build

ENTRYPOINT [ "./bin/darknet" ]
