version: '3.8'

networks:
  shared:
    external:
      name: shared

services:
  brands_detector:
    restart: always
    container_name: brands_detector_${FLASK_ENV}_api
    networks:
      - shared
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - ~/volume/photos:/volume/photos
    build:
      context: ../
      dockerfile: docker/Dockerfile
      args:
        FLASK_ENV: ${FLASK_ENV}
        SECRET_KEY_BASE: ${SECRET_KEY_BASE}
